// CLI 旗标的唯一声明：命令范围、参数类型与解析键名。
// 子命令共用所属命令组的允许集合；帮助解释仍由 commands.mjs 维护。
export const OPTIONS = {
  'dir': { commands: ['init'], type: 'value', key: 'dir' },
  'title': { commands: ['init'], type: 'value', key: 'title' },
  'template': { commands: ['init'], type: 'value', key: 'template' },
  'diagram-type': { commands: ['init'], type: 'value', key: 'diagram-type' },
  'diagram-id': { commands: ['init'], type: 'value', key: 'diagram-id' },
  'node': { commands: ['state', 'trace', 'notice'], type: 'value', key: 'node' },
  'axis': { commands: ['state'], type: 'value', key: 'axis' },
  'value': { commands: ['state'], type: 'value', key: 'value' },
  'reason': { commands: ['state'], type: 'value', key: 'reason' },
  'owner': { commands: ['state'], type: 'value', key: 'owner' },
  'receipt': { commands: ['state'], type: 'value', key: 'receipt' },
  'correction': { commands: ['state'], type: 'boolean', key: 'correction' },
  'sidecar': { commands: ['state', 'diff', 'compile', 'report', 'gate', 'trace', 'lessons', 'notice', 'doctor'], type: 'value', key: 'sidecar' },
  'locator': { commands: ['state'], type: 'value', key: 'locator' },
  'from': { commands: ['state', 'notice'], type: 'value', key: 'from' },
  'to': { commands: ['state'], type: 'value', key: 'to' },
  'with-backlog': { commands: ['state'], type: 'boolean', key: 'withBacklog' },
  'kind': { commands: ['state', 'trace', 'notice'], type: 'value', key: 'kind' },
  'all': { commands: ['state', 'lessons'], type: 'boolean', key: 'all' },
  'ref': { commands: ['state'], type: 'value', key: 'ref' },
  'remove': { commands: ['state'], type: 'boolean', key: 'remove', legacyBooleanValue: true },
  'allow-root': { commands: ['state'], type: 'value', key: 'allow-root' },
  'class': { commands: ['state'], type: 'value', key: 'class' },
  'source': { commands: ['state', 'lessons'], type: 'value', key: 'source' },
  'cutoff': { commands: ['state'], type: 'value', key: 'cutoff' },
  'diagram': { commands: ['state', 'compile', 'gate'], type: 'value', key: 'diagram' },
  'base': { commands: ['diff'], type: 'value', key: 'base' },
  'head': { commands: ['diff'], type: 'value', key: 'head' },
  'since': { commands: ['diff', 'trace'], type: 'value', key: 'since' },
  'out': { commands: ['compile', 'gate'], type: 'value', key: 'out' },
  'previous-receipt': { commands: ['compile'], type: 'value', key: 'previous-receipt' },
  'no-trace': { commands: ['compile', 'report', 'gate'], type: 'boolean', key: 'noTrace' },
  'slice': { commands: ['report'], type: 'value', key: 'slice' },
  'root': { commands: ['report'], type: 'value', key: 'root' },
  'verify': { commands: ['report'], type: 'value', key: 'verify' },
  'code-sha': { commands: ['report'], type: 'value', key: 'code-sha' },
  'spec-sha': { commands: ['report'], type: 'value', key: 'spec-sha' },
  'spec': { commands: ['report'], type: 'value', key: 'spec' },
  'replay': { commands: ['report'], type: 'value', key: 'replay' },
  'brief': { commands: ['report'], type: 'boolean', key: 'brief' },
  'actor': { commands: ['trace'], type: 'value', key: 'actor' },
  'note': { commands: ['trace'], type: 'value', key: 'note' },
  'lesson': { commands: ['lessons'], type: 'value', key: 'lesson' },
  'rule': { commands: ['lessons'], type: 'value', key: 'rule' },
  'recent': { commands: ['lessons'], type: 'value', key: 'recent' },
  'id': { commands: ['lessons', 'notice'], type: 'value', key: 'id' },
  'seat': { commands: ['notice'], type: 'value', key: 'seat' },
  'summary': { commands: ['notice'], type: 'value', key: 'summary' },
  'atlas': { commands: ['doctor'], type: 'value', key: 'atlas' },
  'stats': { commands: ['doctor'], type: 'boolean', key: 'stats' },
};

const commandNames = [...new Set(Object.values(OPTIONS).flatMap((option) => option.commands))];
export const FLAGS = Object.fromEntries(commandNames.map((name) => [
  name, Object.keys(OPTIONS).filter((flag) => OPTIONS[flag].commands.includes(name)),
]));
export const BOOLEAN_FLAGS = Object.fromEntries(Object.entries(OPTIONS)
  .filter(([, option]) => option.type === 'boolean')
  .map(([flag, option]) => [flag, option.key]));
